-- Padroniza os nomes dos templates (proposta revisada em 08/10/2026).
-- Só altera linhas cujo nome e tipo ainda são os antigos. Não desativa nem exclui nada.
-- Para desfazer: entregas/desfazer-nomes-templates.sql
begin;

update "Template" t set nome=v.nome_novo, tipo=v.tipo_novo
from (values
('cmu5ck088000704l5kwarg28o','CHECKLIST DE RECURSOS PARA ATENDIMENTO INICIAL DE EMERGENCIAS','OUTROS','CHECKLIST - Recursos para Atendimento Inicial de Emergências','OUTROS'),
('cmp161pgs0000ewyx1jczx585','Controle Entrega Pos Procedimento','PLANILHA','Controle de Entrega Pós-procedimento','PLANILHA'),
('cmtj3am5k000304kzwh1zeyfj','CONTROLE DE ENVIO E RECEBIMENTO DE MATERIAIS PARA ESTERILIZACAO TERCEIRIZADA','PLANILHA','Controle de Envio e Recebimento de Materiais para Esterilização Terceirizada','PLANILHA'),
('cmp161ph60001ewyxkncxttu0','Controle Orientações Pos','PLANILHA','Controle de Orientações Pós-procedimento','PLANILHA'),
('cmp161phv0003ewyxwhac1oya','Ficha Anamnese Corporal','FICHA','FICHA - Anamnese Corporal','FICHA'),
('cmp161pj10006ewyxn93px6up','Ficha Anamnese Injetaveis','FICHA','FICHA - Anamnese de Injetáveis','FICHA'),
('cmp161pjh0007ewyx4kbyrkm0','Ficha Anamnese Injetaveis Harmonizacao','FICHA','FICHA - Anamnese de Injetáveis em Harmonização','FICHA'),
('cmp161pjy0008ewyxjqzlsvdj','Ficha Anamnese Micropigmentacao Labios','FICHA','FICHA - Anamnese de Micropigmentação de Lábios','FICHA'),
('cmr2jt026000204l16g8ntgpu','FICHA ANAMNESE PROCEDIMENTOS AURICULARES BODY PIERCING','FICHA','FICHA - Anamnese de Procedimentos Auriculares e Body Piercing','FICHA'),
('cmrm48z40000104jthl3f4czs','FICHA - ANAMNESE E AVALIACAO TERAPIAS INJETAVEIS E SOROTERAPIA','FICHA','FICHA - Anamnese e Avaliação de Terapias Injetáveis e Soroterapia','FICHA'),
('cmpwyga80000304l8aldpwbw1','FICHA DE ANAMNESE SAUDE DA MULHER','FICHA','FICHA - Anamnese em Saúde da Mulher','FICHA'),
('cmqw5wp5n000004l4xt2orcbt','FICHA ANAMNESE ESTETICA INTEGRATIVA','FICHA','FICHA - Anamnese Estética Integrativa','FICHA'),
('cmp161pik0005ewyx5xqpp47x','Ficha Anamnese Facial','FICHA','FICHA - Anamnese Facial','FICHA'),
('cmtvo5av3000004k1ds4o9rrv','FICHA - ATENDIMENTO E EVOLUCAO ENEMA E LAVAGEM INTESTINAL','FICHA','FICHA - Atendimento e Evolução de Enema e Lavagem Intestinal','FICHA'),
('cmtvo5cxv000104k1co2qax16','FICHA - ATENDIMENTO E EVOLUCAO OZONIOTERAPIA','FICHA','FICHA - Atendimento e Evolução de Ozonioterapia','FICHA'),
('cmtvo5ec3000204k1yg7xcf5c','FICHA - ATENDIMENTO E EVOLUCAO TERAPIAS INTEGRATIVAS','FICHA','FICHA - Atendimento e Evolução de Terapias Integrativas','FICHA'),
('cmqzbvspj000004kz741lwnxu','FICHA DE AVALIACAO CORPORAL E POS OPERATORIO','FICHA','FICHA - Avaliação Corporal e Pós-operatório','FICHA'),
('cmujm0qcw000304l2rkvl5bvo','FICHA - AVALIACAO E EVOLUCAO CAPILAR E DO COURO CABELUDO','FICHA','FICHA - Avaliação e Evolução Capilar e do Couro Cabeludo','FICHA'),
('548494ed-3a6a-4c3c-809b-df97037f0ae3','FICHA - AVALIACAO NUTRICIONAL','FICHA','FICHA - Avaliação Nutricional','FICHA'),
('cmr9dugkr000004kvvp2ux71e','FICHA - AVALIACAO REMOCAO DE PIGMENTACAO ESTETICA','FICHA','FICHA - Avaliação para Remoção de Pigmentação Estética','FICHA'),
('b12de3f0-1e72-4e74-a1bf-5009b829d05f','FICHA - AVALIACAO PEDIATRICA FURO ORELHA','FICHA','FICHA - Avaliação Pediátrica para Furo de Orelha','FICHA'),
('cmqw5j7ij000004l5nyup02t2','FICHA DE AVALIACAO PODOLOGICA','FICHA','FICHA - Avaliação Podológica','FICHA'),
('cmtvo5tru000704k1wo944xiz','FICHA - CADASTRO ANAMNESE E AVALIACAO ESTETICA','FICHA','FICHA - Cadastro, Anamnese e Avaliação Estética','FICHA'),
('cmu5ck182000804l52jxr615a','FICHA - MONITORAMENTO DA TERAPIA INFUSIONAL E DO ACESSO VENOSO PERIFERICO','FICHA','FICHA - Monitoramento da Terapia Infusional e do Acesso Venoso Periférico','FICHA'),
('cmtvo5qzz000604k1oieb3mwy','FICHA - PERIMETRIA E EVOLUCAO CORPORAL','FICHA','FICHA - Perimetria e Evolução Corporal','FICHA'),
('cmtvo5jgq000404k1d6hhaoh2','FOLHA DE EVOLUCAO CORPORAL','OUTROS','FOLHA - Evolução Corporal','OUTROS'),
('cmtvo5gvf000304k1yic60j8m','FOLHA DE EVOLUCAO SOBRANCELHAS E DEPILACAO','OUTROS','FOLHA - Evolução de Sobrancelhas e Depilação','OUTROS'),
('cmtvo5o6d000504k1vl6izmlr','FOLHA DE EVOLUCAO FACIAL','OUTROS','FOLHA - Evolução Facial','OUTROS'),
('cmp161pkb0009ewyxjeq9m7pp','FORM EVENTO ADVERSO','OUTROS','FORMULÁRIO - Evento Adverso','OUTROS'),
('cmplfoue6000004kvldy4gsuq','Guia Utilizacao Pasta Sanitaria','GUIA','Guia de Utilização da Pasta Sanitária','GUIA'),
('cmp161pl5000bewyxi7p6v4mu','MBP Embelezamento','MBP','MBP - Embelezamento','MBP'),
('cmpei1399002f3c1omed231l7','MBP Servico Saude','MBP','MBP - Serviço de Saúde','MBP'),
('cmp161pmf000eewyxq25bcmz7','Planilha Controle Temperatura','PLANILHA','PLANILHA - Controle de Temperatura','PLANILHA'),
('cmp161pms000fewyx8lzh3fvm','Planilha Limpeza Desinfeccao','PLANILHA','PLANILHA - Limpeza e Desinfecção','PLANILHA'),
('cmp161pn8000gewyxdtqdr60d','PLANILHA RASTREABILIDADE PRODUTOS','PLANILHA','PLANILHA - Rastreabilidade de Produtos','PLANILHA'),
('cmp161pnl000hewyx7grjvyui','Plano Contingencia','OUTROS','Plano de Contingência','OUTROS'),
('cmp161pxd001aewyxziinh88h','POP Acidentes Material Biologico','POP','POP - Acidentes com Material Biológico','POP'),
('cmqdshwet000904lata0cef12','POP ACOMPANHAMENTO PRE E POS PROCEDIMENTO ESTETICO','POP','POP - Acompanhamento Pré e Pós-procedimento Estético','POP'),
('cmu5cjq4l000004l5do17k9pv','POP - ACUPUNTURA','POP','POP - Acupuntura','POP'),
('cmr6b3yxv000004ky1egw11a2','ADMINISTRAÇÃO DE ANESTÉSICO LOCAL','OUTROS','POP - Administração de Anestésico Local','POP'),
('cmr6b41xo000304kykyndukaj','POP ADMINISTRACAO ANESTESICO LOCAL SAUDE REPRODUTIVA','POP','POP - Administração de Anestésico Local em Saúde Reprodutiva','POP'),
('cmp161pnx000iewyxks69yjao','POP - AFERICAO E MONITORAMENTO DE SINAIS VITAIS','POP','POP - Aferição e Monitoramento de Sinais Vitais','POP'),
('038c1c9a-2065-4b04-8d8b-cd22e9027716','POP - ALTA FREQUENCIA','POP','POP - Alta Frequência','POP'),
('cmqr7bibe000d04l1fy5tsxly','POP APLICACAO DE ENZIMAS','POP','POP - Aplicação de Enzimas','POP'),
('cmrdf1bp7000004l2hqf4yage','POP - APLICACAO DE MEDICACAO IM E EV','POP','POP - Aplicação de Medicação IM e EV','POP'),
('cmpeo7zwy0000t81ocm7pk6bt','POP - AROMATERAPIA','POP','POP - Aromaterapia','POP'),
('cmp161po8000jewyxaumjz98k','POP - ASPIRACAO DE VIAS AEREAS','POP','POP - Aspiração de Vias Aéreas','POP'),
('cmp161pol000kewyxt9ea0vbo','POP - ATENDIMENTO DOMICILIAR','POP','POP - Atendimento Domiciliar','POP'),
('cmpwygd8t000804l8hl084lsx','POP ATENDIMENTOS E PROCEDIMENTOS EM SAUDE DA MULHER','POP','POP - Atendimentos e Procedimentos em Saúde da Mulher','POP'),
('cmr2hyhaf000j04jrvpchocsz','POP - AURICULOTERAPIA','POP','POP - Auriculoterapia','POP'),
('cmu5ck5wk000b04l5d6wu72di','POP - AVALIACAO CAPILAR','POP','POP - Avaliação Capilar','POP'),
('cmpei0mu9002b3c1oghqxgm7q','POP - AVALIACAO E ANALISE DE PELE','POP','POP - Avaliação e Análise de Pele','POP'),
('cmpwyg9i9000104l8iz76nvvv','POP AVALIACAO FISIOTERAPEUTICA DERMATOFUNCIONAL','POP','POP - Avaliação Fisioterapêutica Dermatofuncional','POP'),
('cmpei0mug002c3c1od7u4w5ug','POP - AVALIACAO NUTRICIONAL E DIETETICA','POP','POP - Avaliação Nutricional e Dietética','POP'),
('cmu2mbvi7000104la7hsebxnn','POP - AVALIACAO POR BIOIMPEDANCIA','POP','POP - Avaliação por Bioimpedância','POP'),
('cmp161pyf001bewyxc1g96y2g','POP BB Glow','POP','POP - BB Glow','POP'),
('cmr2hygeb000i04jr00byip2c','POP - BIOESTIMULACAO AUTOLOGA','POP','POP - Bioestimulação Autóloga','POP'),
('cmq7woc1z000104js0hbtg86v','POP BIOESTIMULADORES DE COLAGENO FACIAL E CORPORAL','POP','POP - Bioestimuladores de Colágeno Facial e Corporal','POP'),
('cmr2hyecf000g04jr4v3vt1ws','POP - BIORREMODELADORES TECIDUAIS','POP','POP - Biorremodeladores Teciduais','POP'),
('cmr2hyc48000e04jr0z0cmd4l','POP - BODY PIERCING','POP','POP - Body Piercing','POP'),
('cmqzbvtrj000104kz99t1kftb','POP BOTA COMPRESSIVA PRESSOTERAPIA','POP','POP - Bota Compressiva (Pressoterapia)','POP'),
('cmszzcvl9000104lcfpjr37lt','POP - BROW LAMINATION','POP','POP - Brow Lamination','POP'),
('cmqr7bgi6000b04l1zkv2syrk','POP CARBOXITERAPIA','POP','POP - Carboxiterapia','POP'),
('cmqdshw4b000804lah1j4gtol','POP CAVITACAO LIPO SEM CORTE','POP','POP - Cavitação (Lipo sem Corte)','POP'),
('cmr2jswld000004l14kt1tf5y','POP - CAVITACAO ULTRASSONICA','POP','POP - Cavitação Ultrassônica','POP'),
('cmqfohttz000g04kwszs0e6pz','POP CLAREAMENTO DE MELASMA MELANOSE E MANCHAS SENIS','POP','POP - Clareamento de Melasma, Melanose e Manchas Senis','POP'),
('a631286d-6405-44bd-bf64-133edc4ac6a3','POP - CLAREAMENTO INTIMO','POP','POP - Clareamento Íntimo','POP'),
('cmp161pow000lewyxsrto6zwx','POP - COLETA DE AMOSTRAS LABORATORIAIS E FLEBOTOMIA','POP','POP - Coleta de Amostras Laboratoriais e Flebotomia','POP'),
('cmr6b40sn000204kye3b5g8c3','POP COLETA CITOPATOLOGICO MEIO LIQUIDO DNA HPV','POP','POP - Coleta de Citopatológico em Meio Líquido e DNA-HPV','POP'),
('cmp161pp6000mewyxy4nmic1v','POP - CONSULTA DE ENFERMAGEM','POP','POP - Consulta de Enfermagem','POP'),
('cmu5ck3sr000904l5vso6ri35','POP - CONSULTA E ACOMPANHAMENTO FARMACEUTICO','POP','POP - Consulta e Acompanhamento Farmacêutico','POP'),
('cmpei0mul002d3c1ob6gyc4pk','POP - CONSULTA E PRONTUARIO','POP','POP - Consulta e Prontuário','POP'),
('cmrdf1csg000104l25fr6hb26','POP - CONTROLE DA GLICEMIA','POP','POP - Controle da Glicemia','POP'),
('cmp161pz9001dewyx6ajrhui5','POP CONTROLE POTABILIDADE AGUA','POP','POP - Controle de Potabilidade da Água','POP'),
('cmp161pzp001eewyxyuapwezx','POP Controle Vetores Pragas','POP','POP - Controle de Vetores e Pragas','POP'),
('cmq86v34c000604l4bf2zrm0c','POP CORRENTE AUSSIE E CORRENTE RUSSA FORTALECIMENTO MUSCULAR','POP','POP - Corrente Aussie e Corrente Russa para Fortalecimento Muscular','POP'),
('5d64a035-e784-4cc7-9241-3bbd3104ce48','POP - CRIOLIPOLISE','POP','POP - Criolipólise','POP'),
('cmp161ppg000newyx63w06pgz','POP - CUIDADOS COM ESTOMIAS','POP','POP - Cuidados com Estomias','POP'),
('cmp161ppu000oewyxg6vbdybj','POP - CUIDADOS COM SONDA ENTERAL','POP','POP - Cuidados com Sonda Enteral','POP'),
('cmp161pq6000pewyx84u53fma','POP - CUIDADOS COM SONDA VESICAL','POP','POP - Cuidados com Sonda Vesical','POP'),
('cmp161pqg000qewyx68dnvcg8','POP - CUIDADOS COM TRAQUEOSTOMIA','POP','POP - Cuidados com Traqueostomia','POP'),
('cmp161pqq000rewyxypnwxnn1','POP - CURATIVO E CUIDADOS COM FERIDAS','POP','POP - Curativo e Cuidados com Feridas','POP'),
('cmqfohw9s000j04kwagueylj8','POP DEPILACAO A LASER','POP','POP - Depilação a Laser','POP'),
('cmqfohvh5000i04kwldpd6jkc','POP DEPILACAO A LUZ PULSADA','POP','POP - Depilação à Luz Pulsada','POP'),
('cmquuqj1h000504k1n59lbf0k','POP DEPILACAO ROLL ON','POP','POP - Depilação com Roll-on','POP'),
('cmpeo7zxb0001t81oy4pu6a7u','POP - DERMAPLANING','POP','POP - Dermaplaning','POP'),
('cmquuqi4d000404k1m1g1hkhx','POP DESIGN DE SOBRANCELHAS','POP','POP - Design de Sobrancelhas','POP'),
('cmqdshva8000604la72623yqg','POP DETOX CORPORAL','POP','POP - Detox Corporal','POP'),
('cmpeo7zxe0002t81oso9hbzn4','POP - DRENAGEM FACIAL E CORPORAL','POP','POP - Drenagem Facial e Corporal','POP'),
('cmr2hyd2b000f04jrvilf2uou','POP - DRENAGEM LINFATICA','POP','POP - Drenagem Linfática','POP'),
('f66bd727-e58d-417a-84a9-193dfedbc53a','POP - ELETROESTIMULACAO NEUROMUSCULAR','POP','POP - Eletroestimulação Neuromuscular','POP'),
('cmujm0okl000204l2l9w4iula','POP - ELETROLIFTING','POP','POP - Eletrolifting','POP'),
('cmu5ck6pm000c04l5xyckpg0z','POP - ELETROPORACAO ESTETICA FACIAL CORPORAL E CAPILAR','POP','POP - Eletroporação Estética Facial, Corporal e Capilar','POP'),
('cmqdshvtn000704lawckwq96z','POP ELETROTERAPIA ESTETICA CORPORAL','POP','POP - Eletroterapia Estética Corporal','POP'),
('cmu2mbx4e000204lam51hl2tp','POP - ENCAMINHAMENTO E TRANSFERENCIA DO PACIENTE','POP','POP - Encaminhamento e Transferência do Paciente','POP'),
('388c4a6f-d62a-41ee-b512-4a3461110834','POP - ENDERMOTERAPIA','POP','POP - Endermoterapia','POP'),
('cmtj3akc5000104kz4hfyi481','POP - ENVIO RECEBIMENTO E RASTREABILIDADE DE MATERIAIS SUBMETIDOS A ESTERILIZACAO TERCEIRIZADA','POP','POP - Envio, Recebimento e Rastreabilidade de Materiais Submetidos à Esterilização Terceirizada','POP'),
('cmu5ekvth000004l6zf837w02','POP - EPILACAO A CERA','POP','POP - Epilação à Cera','POP'),
('cmp161q03001fewyxl6ljyc8h','POP Estrias Plasma Bioestimulador','POP','POP - Estrias com Plasma Bioestimulador','POP'),
('cmpwyg9wo000204l8v2xxlqws','POP EXTENSAO DE CILIOS','POP','POP - Extensão de Cílios','POP'),
('cmppjpqop000404kv2rtqdooa','POP - FIOS DE PDO','POP','POP - Fios de PDO','POP'),
('cmp161pr1000sewyxw82gjq0w','POP - FIOS DE SUSTENTACAO PDO','POP','POP - Fios de Sustentação de PDO','POP'),
('cmp161prd000tewyx2xwsryxm','POP - FOTOBIOMODULACAO','POP','POP - Fotobiomodulação','POP'),
('cmr2hyi6x000k04jrxecft9tl','POP FOTOTERAPIA LEDTERAPIA','POP','POP - Fototerapia (Ledterapia)','POP'),
('cmqr7bem3000904l10wwsnubc','POP FOTOTERAPIA COM LED','POP','POP - Fototerapia com LED','POP'),
('92b17d96-4bc8-4315-8ed2-7097460e5c0d','POP - FURO DE ORELHA CRIANCAS ADULTOS','POP','POP - Furo de Orelha em Crianças e Adultos','POP'),
('cmplfq58b000204kvg89jipfh','POP - FURO DE ORELHA HUMANIZADO','POP','POP - Furo de Orelha Humanizado','POP'),
('cmp161q0d001gewyx28kwh3ak','POP Gerenciamento Residuos','POP','POP - Gerenciamento de Resíduos','POP'),
('cmplfpr0k000104kvix8itpa7','POP - GESTAO DE EQUIPAMENTOS','POP','POP - Gestão de Equipamentos','POP'),
('cmp161prp000uewyxfxo5v54u','POP - GESTAO DE SEGURANCA LASER E LED','POP','POP - Gestão de Segurança em Laser e LED','POP'),
('cmu2mbulv000004la67t1vkvo','POP - GESTAO DO PRONTUARIO IDENTIFICACAO DO PACIENTE E REGISTROS ASSISTENCIAIS MULTIPROFISSIONAIS','POP','POP - Gestão do Prontuário, Identificação do Paciente e Registros Assistenciais Multiprofissionais','POP'),
('cmp161q1b001jewyxg7zhlmb8','POP Harmonizacao Plasma Gel','POP','POP - Harmonização com Plasma Gel','POP'),
('cmq7u02z1000004kzq67xm1bd','POP Harmonizacao Corporal Glutea','POP','POP - Harmonização Corporal Glútea','POP'),
('cmp161q10001iewyxyewulz86','POP Harmonizacao Facial Global','POP','POP - Harmonização Facial Global','POP'),
('cmq86v3s0000804l4dl20w895','POP HARMONIZACAO INTIMA FEMININA','POP','POP - Harmonização Íntima Feminina','POP'),
('cmp161q1p001kewyxs4bijhlf','POP Hemoderivados PRP PRF','POP','POP - Hemoderivados (PRP e PRF)','POP'),
('cmpeo7zxj0003t81oe0gjjf77','POP - HIDRATACAO FACIAL','POP','POP - Hidratação Facial','POP'),
('8702dbce-c8f3-4702-a85e-d69f05d21c61','POP - HIDROLIPOCLASIA NAO ASPIRATIVA','POP','POP - Hidrolipoclasia Não Aspirativa','POP'),
('cmq86v1rb000204l4lskxbqu7','POP HIFU INTIMO ULTRASSOM MICRO E MACROFOCADO INTIMO','POP','POP - HIFU Íntimo (Ultrassom Micro e Macrofocado)','POP')
) v(id,nome_atual,tipo_atual,nome_novo,tipo_novo)
where t.id=v.id and t.nome=v.nome_atual and t.tipo=v.tipo_atual
;

update "Template" t set nome=v.nome_novo, tipo=v.tipo_novo
from (values
('cmp161q21001lewyx90fz1f0v','POP Higienizacao Maos','POP','POP - Higienização das Mãos','POP'),
('cmu2mbzkw000404la1s3s51dl','POP - INFILTRACAO INTRA ARTICULAR E PERIARTICULAR','POP','POP - Infiltração Intra-articular e Periarticular','POP'),
('cmr6b3zy9000104kyup5fmicg','POP INSERCAO DISPOSITIVO INTRAUTERINO DIU','POP','POP - Inserção de Dispositivo Intrauterino (DIU)','POP'),
('cmr6d7njo000104jmsp9x4bnn','POP INSERCAO IMPLANTE CONTRACEPTIVO SUBDERMICO IMPLANON NXT','POP','POP - Inserção de Implante Contraceptivo Subdérmico (Implanon NXT)','POP'),
('cmp161q2f001mewyxd0zzrh2m','POP Intercorrencias Emergencias','POP','POP - Intercorrências e Emergências','POP'),
('c5a9108a-51bb-4ab4-a40a-49d281b27173','POP - INTRADERMOTERAPIA CAPILAR','POP','POP - Intradermoterapia Capilar','POP'),
('cmp161ps1000vewyx8xs9hbag','POP - INTRADERMOTERAPIA PRESSURIZADA','POP','POP - Intradermoterapia Pressurizada','POP'),
('cmp161psc000wewyxjbysy1lc','POP - JATO DE PLASMA','POP','POP - Jato de Plasma','POP'),
('cmqr7bfia000a04l1hrb1x07y','POP LASER CO2 E LASER CO2 FRACIONADO','POP','POP - Laser CO2 e Laser CO2 Fracionado','POP'),
('cmqr7bhho000c04l1zj84wuqs','POP LASER DE TULIO 1927NM LAVIEEN','POP','POP - Laser de Túlio 1927 nm (Lavieen)','POP'),
('cmq86v4jb000a04l4d6exl4ku','POP LASERTERAPIA LEDTERAPIA MASCARA','POP','POP - Laserterapia e Ledterapia com Máscara','POP'),
('cmp2wj96k0000vkyx8kvf7dtn','POP - LASERTERAPIA EM AFECCOES','POP','POP - Laserterapia em Afecções','POP'),
('efc1eea5-bd23-46e2-ad49-77a10ea49a6b','POP - LASERTERAPIA POS CIRURGICA','POP','POP - Laserterapia Pós-cirúrgica','POP'),
('10cc6598-dd9b-442e-b3e6-fddf08e1f340','POP - LASERTERAPIA POS FURO E PIERCING','POP','POP - Laserterapia Pós-furo e Piercing','POP'),
('cmszzcshy000204i5yav6l3gb','POP - LASH LIFTING','POP','POP - Lash Lifting','POP'),
('cmpei0mut002e3c1ocq9qt2c1','POP - LEDTERAPIA','POP','POP - Ledterapia','POP'),
('cmqdshwph000a04lak632ab5x','POP LIBERACAO MIOFASCIAL COM VENTOSA','POP','POP - Liberação Miofascial com Ventosa','POP'),
('cmp161q2s001newyxjjc9uwsd','POP Limpeza Pele','POP','POP - Limpeza de Pele','POP'),
('cmqfohumr000h04kw2s92z431','POP LIMPEZA DE PELE COM RECURSOS ELETROTERAPEUTICOS','POP','POP - Limpeza de Pele com Recursos Eletroterapêuticos','POP'),
('cmp161q40001qewyxqabai1xm','POP Limpeza Superficies','POP','POP - Limpeza de Superfícies','POP'),
('cmp161q3f001oewyxhg8dyoek','POP LIMPEZA PURIFICADOR AGUA','POP','POP - Limpeza do Purificador de Água','POP'),
('cmp161q3p001pewyxcbvkcczz','POP Limpeza Refrigerador','POP','POP - Limpeza do Refrigerador','POP'),
('cmp2wj96z0001vkyx4fy7m6q1','POP - LIMPEZA E MANUTENCAO CLIMATIZACAO','POP','POP - Limpeza e Manutenção da Climatização','POP'),
('cmp161q4c001rewyx2nmpuu5o','POP Lip Glow','POP','POP - Lip Glow','POP'),
('cmq86v3hq000704l4kzazwpik','POP LIPO ENZIMATICA GORDURA LOCALIZADA E GLUTEOS','POP','POP - Lipo Enzimática de Gordura Localizada e Glúteos','POP'),
('f6a779e6-fcff-45fe-95d7-191edb2498b1','POP - LIPO ENZIMATICA DE PAPADA','POP','POP - Lipo Enzimática de Papada','POP'),
('cmpwygcco000704l8us9yj8go','POP LOBULOMODELACAO LOBULOPLASTIA NAO CIRURGICA','POP','POP - Lobulomodelação (Lobuloplastia Não Cirúrgica)','POP'),
('cmrdf1dx4000204l2l959l97v','POP - MANEJO DE BOLSA DE COLOSTOMIA','POP','POP - Manejo de Bolsa de Colostomia','POP'),
('cmu5ck4xy000a04l5rag44gb4','POP - MANICURE E PEDICURE','POP','POP - Manicure e Pedicure','POP'),
('69fdbffd-85b2-4ea9-9db7-db3dcf6c0607','POP - MANTA TERMICA','POP','POP - Manta Térmica','POP'),
('cmp161q4m001sewyxhx0onogt','POP Manutencao Equipamentos','POP','POP - Manutenção de Equipamentos','POP'),
('cmpeo7zxn0004t81ooulynw2a','POP - MASSAGEM MODELADORA','POP','POP - Massagem Modeladora','POP'),
('cmquuqg8y000204k11duvxp3i','POP MASSAGEM TERAPEUTICA RELAXANTE E REDUTORA','POP','POP - Massagem Terapêutica Relaxante e Redutora','POP'),
('cmp161pt0000yewyx4gt1q8kn','POP - MESOTERAPIA E INTRADERMOTERAPIA','POP','POP - Mesoterapia e Intradermoterapia','POP'),
('cmp2wj97d0002vkyx2439a39d','POP - MICROAGULHAMENTO','POP','POP - Microagulhamento','POP'),
('cmquuqffh000104k13kszlidc','POP MICROPIGMENTACAO COM DERMOGRAFO','POP','POP - Micropigmentação com Dermógrafo','POP'),
('cmp161q4y001tewyx15y9rhuc','POP Micropigmentacao Labial','POP','POP - Micropigmentação Labial','POP'),
('765724f8-419d-41b9-a206-3ffbb770b46e','POP - MICROTOX','POP','POP - Microtox','POP'),
('cmtcu43vr000204l1rssnyjmu','POP - NEBULIZACAO E INALOTERAPIA','POP','POP - Nebulização e Inaloterapia','POP'),
('d74334d3-19f8-477d-91e0-1c59eaf5864b','POP - ONDAS DE CHOQUE','POP','POP - Ondas de Choque','POP'),
('cmppjpr9o000504kvg7r3bhmz','POP - OTOMODELACAO','POP','POP - Otomodelação','POP'),
('cmppgtqev000104jy0qs5wcqa','POP - OZONIOTERAPIA','POP','POP - Ozonioterapia','POP'),
('cmu4onq9o000104jtr7hrl8yi','POP - PEELING DE DIAMANTE MICRODERMOABRASAO','POP','POP - Peeling de Diamante (Microdermoabrasão)','POP'),
('cmq86v0x5000104l489ej011q','POP PEELING ELETRICO FACIAL E CORPORAL','POP','POP - Peeling Elétrico Facial e Corporal','POP'),
('cmq86v0li000004l4aags3wr0','POP PEELING ELETRICO INTIMO','POP','POP - Peeling Elétrico Íntimo','POP'),
('cmqr7azx5000004l12gv8tvky','POP PEELING ENZIMATICO','POP','POP - Peeling Enzimático','POP'),
('cmpeo7zxs0005t81o0i48a0fj','POP - PEELING FISICO','POP','POP - Peeling Físico','POP'),
('cmq86v2fh000404l45c2ao1is','POP PEELING QUIMICO FACIAL E CORPORAL RETINOL 10 E MANDELICO 30','POP','POP - Peeling Químico Facial e Corporal com Retinol 10% e Mandélico 30%','POP'),
('cmq86v227000304l429k6svq0','POP PEELING QUIMICO INTIMO','POP','POP - Peeling Químico Íntimo','POP'),
('cmujm0m39000004l23955rpio','POP - PEELING ULTRASSONICO','POP','POP - Peeling Ultrassônico','POP'),
('cmp161pta000zewyx2k0hr7sj','POP - PEELINGS QUIMICOS','POP','POP - Peelings Químicos','POP'),
('cmp161ptm0010ewyx50a2lou0','POP - PEELINGS QUIMICOS ACIDO TRICLOROACETICO','POP','POP - Peelings Químicos com Ácido Tricloroacético','POP'),
('cmp161pu30011ewyxm4pts5jd','POP - PEIM ESCLEROTERAPIA','POP','POP - PEIM (Escleroterapia)','POP'),
('cmr2hy8zo000b04jrc79rsabx','POP - PERFURACAO AURICULAR HUMANIZADA','POP','POP - Perfuração Auricular Humanizada','POP'),
('cmr2hyb4w000d04jrdd1uqvsb','POP - PERFURACAO DE LOBULO E CARTILAGEM AURICULAR','POP','POP - Perfuração de Lóbulo e Cartilagem Auricular','POP'),
('cmr2hyfet000h04jrrt85fwvs','POP - PLASMA GEL AUTOLOGO','POP','POP - Plasma Gel Autólogo','POP'),
('cmquuqhbm000304k1odtm2ipp','POP PODOLOGIA','POP','POP - Podologia','POP'),
('cmqwf7ygg000304jsme9ash0z','POP POS OPERATORIO ESTETICO PROTOCOLO COMBINADO','POP','POP - Pós-operatório Estético (Protocolo Combinado)','POP'),
('cmp161q58001uewyx1i1ynivc','POP Preenchimento Acido Hialuronico','POP','POP - Preenchimento com Ácido Hialurônico','POP'),
('cmqzcsi5u000004jygm3wudhg','POP PREENCHIMENTO DERMICO ACIDO HIALURONICO','POP','POP - Preenchimento Dérmico com Ácido Hialurônico','POP'),
('cmp161q5h001vewyxqmx1hiy4','POP Preenchimento Labial','POP','POP - Preenchimento Labial','POP'),
('cmp161pug0012ewyx97y76yyf','POP - PRESCRICAO DE ENFERMAGEM','POP','POP - Prescrição de Enfermagem','POP'),
('cmp161q5w001wewyxfpgqldks','POP Prevencao Oclusao Vascular','POP','POP - Prevenção de Oclusão Vascular','POP'),
('cmp161pur0013ewyxnwx0fwih','POP - PREVENCAO E TRATAMENTO DE INTERCORRENCIAS VENOSAS','POP','POP - Prevenção e Tratamento de Intercorrências Venosas','POP'),
('cmp161q67001xewyx7jfnabtn','POP Processamento Materiais','POP','POP - Processamento de Materiais','POP'),
('cmp161pv20014ewyxqaqvnbw3','POP - PROCESSO DE ENFERMAGEM','POP','POP - Processo de Enfermagem','POP'),
('cmq882dsh000004l54szqp7wj','POP PUMP UP NOS GLUTEOS COM RADIOFREQUENCIA','POP','POP - Pump Up nos Glúteos com Radiofrequência','POP'),
('cmu5ck8lt000d04l5wgcc04rw','POP - PUNCAO MANUTENCAO E RETIRADA DE ACESSO VENOSO PERIFERICO','POP','POP - Punção, Manutenção e Retirada de Acesso Venoso Periférico','POP'),
('4ebd051a-b820-4ae8-b897-37b1308ee357','POP - RADIOFREQUÊNCIA','POP','POP - Radiofrequência','POP'),
('cmq86v487000904l40l7sw5ph','POP RADIOFREQUENCIA INTIMA ULTRAMED INTIMY','POP','POP - Radiofrequência Íntima (Ultramed Intimy)','POP'),
('cmq86v2t5000504l4dmnc6ji4','POP RASTREABILIDADE DE INJETAVEIS LOTES E INSUMOS','POP','POP - Rastreabilidade de Injetáveis, Lotes e Insumos','POP'),
('cmp161q6j001yewyxw13n0ta2','POP Recebimento Armazenamento','POP','POP - Recebimento e Armazenamento','POP'),
('cmqwf7zcy000404jsvzk0smzr','POP REDUCAO DE MEDIDAS PROTOCOLO COMBINADO','POP','POP - Redução de Medidas (Protocolo Combinado)','POP'),
('cmqwf7uc8000004jszk9voo9m','POP REDUCAO DE MEDIDAS RADIOFREQUENCIA BOTA COMPRESSIVA E MANTA TERMICA','POP','POP - Redução de Medidas com Radiofrequência, Bota Compressiva e Manta Térmica','POP'),
('cmtu623zf000404ie3trkp9cz','POP - REFLEXOTERAPIA PODAL','POP','POP - Reflexoterapia Podal','POP'),
('cmqfohs1f000e04kw7z2uq6ax','POP REJUVENESCIMENTO FACIAL','POP','POP - Rejuvenescimento Facial','POP'),
('cmr2hy7t0000a04jrn8go1jo7','POP - REJUVENESCIMENTO INTIMO EXTERNO','POP','POP - Rejuvenescimento Íntimo Externo','POP'),
('cmr9dujbr000204kva1xu38vf','POP - REMOCAO DE PIGMENTACAO ESTETICA','POP','POP - Remoção de Pigmentação Estética','POP'),
('cmp161pve0015ewyxhgwqo0je','POP - RETIRADA DE PONTOS CIRURGICOS','POP','POP - Retirada de Pontos Cirúrgicos','POP'),
('cmr2hy9ws000c04jrymnzc6cu','POP - REVITALIZACAO CORRECAO E FECHAMENTO DE LOBULO AURICULAR','POP','POP - Revitalização, Correção e Fechamento de Lóbulo Auricular','POP'),
('cmp161q6u001zewyxw9b8mfc1','POP Rinomodelacao','POP','POP - Rinomodelação','POP'),
('cmp161pvw0016ewyxkr7ck2ko','POP - SKINBOOSTER','POP','POP - Skinbooster','POP'),
('cmu5el171000404l6jcwhroti','POP - SPA DOS PES PLASTICA DOS PES','POP','POP - Spa dos Pés (Plástica dos Pés)','POP'),
('cmsvr27ya000004l1fns0zo3s','POP - SUBCISAO','POP','POP - Subcisão','POP'),
('c1e8e472-6991-4bc1-bf8b-12b167395802','POP - TAPING POS CIRURGICO','POP','POP - Taping Pós-cirúrgico','POP'),
('cmtu61zt5000204ie0kgf8mwa','POP - TECARTERAPIA','POP','POP - Tecarterapia','POP'),
('cmqfohr5q000d04kw0is67ivp','POP TERAPIA CAPILAR ALOPECIA E CALVICIE','POP','POP - Terapia Capilar para Alopecia e Calvície','POP'),
('cmtu61x72000004ie3383fgm8','POP - TERAPIA DE FLORAIS','POP','POP - Terapia de Florais','POP'),
('cmp161pwb0017ewyx34fnr8sc','POP - TERAPIA INJETAVEL E ADMINISTRACAO DE MEDICAMENTOS','POP','POP - Terapia Injetável e Administração de Medicamentos','POP'),
('cmp161pwp0018ewyxol384zt4','POP - TERAPIA ORTOMOLECULAR INTRAVENOSA','POP','POP - Terapia Ortomolecular Intravenosa','POP'),
('f3262c11-f384-4f55-9e6e-bc741d5f972c','POP - TERAPIAS COMBINADAS','POP','POP - Terapias Combinadas','POP'),
('cmqdshx01000b04laubauv4rq','POP TERAPIAS MANUAIS CORPORAIS','POP','POP - Terapias Manuais Corporais','POP'),
('cmq9g7aj1000004kyqyt2nhoo','POP TERAPIAS REGENERATIVAS PDRN EXOSSOMOS E REGENERADORES CELULARES','POP','POP - Terapias Regenerativas (PDRN, Exossomos e Regeneradores Celulares)','POP'),
('cmp161px00019ewyx47a5of41','POP - TESTES RAPIDOS DIAGNOSTICOS','POP','POP - Testes Rápidos Diagnósticos','POP'),
('cmp161q740020ewyxqkaghz6k','POP Toxina Botulinica','POP','POP - Toxina Botulínica','POP'),
('cmqfohsxq000f04kwcit46o3f','POP TRATAMENTO DE CICATRIZES DE ACNE','POP','POP - Tratamento de Cicatrizes de Acne','POP'),
('cmqdshuzp000504lakvglzkwr','POP TRATAMENTO DE ESTRIAS','POP','POP - Tratamento de Estrias','POP'),
('1d96937f-ad1e-4935-80c5-cd313e7ffce9','POP - ULTRASSOM','POP','POP - Ultrassom','POP'),
('cmpwygc2f000604l8tb5emmk9','POP ULTRASSOM MICROFOCADO E MACROFOCADO','POP','POP - Ultrassom Microfocado e Macrofocado','POP'),
('cmp161q7f0021ewyxofpalfjd','POP Uso EPIs','POP','POP - Uso de EPIs','POP'),
('cmq7wob8k000004jsl9bklv8e','POP VALIDACAO E MONITORAMENTO DA ESTERILIZACAO','POP','POP - Validação e Monitoramento da Esterilização','POP'),
('cmqsguajl000004k1tdyx5btm','POP VAPOR DE OZONIO','POP','POP - Vapor de Ozônio','POP'),
('cmu5ekyci000204l6ar2tibbz','POP - VENTOSATERAPIA','POP','POP - Ventosaterapia','POP'),
('cmqwblueb000004ju1e68qbxp','PROTOCOLO INTERCORRENCIAS SERVICO NAO INVASIVO','OUTROS','PROTOCOLO - Intercorrências em Serviço Não Invasivo','OUTROS'),
('cmp161q8w0025ewyxb0mx8je4','Receituario Pos Procedimento','RECEITUARIO','Receituário Pós-procedimento','RECEITUARIO'),
('cmp161q980026ewyx541gd3lt','REGISTRO ESTERILIZACAO','OUTROS','REGISTRO - Esterilização','OUTROS'),
('cmtj3ajgs000004kz0bqt8hja','REGISTRO DE MANUTENCAO CALIBRACAO E SEGURANCA ELETRICA DOS EQUIPAMENTOS','OUTROS','REGISTRO - Manutenção, Calibração e Segurança Elétrica dos Equipamentos','OUTROS'),
('cmu2mc0ka000504la0e7vpmox','REGISTRO DO PROCEDIMENTO DE INFILTRACAO INTRA E PERIARTICULAR','OUTROS','REGISTRO - Procedimento de Infiltração Intra e Periarticular','OUTROS'),
('cmszzcumm000004lck8vymyn9','REGISTRO TREINAMENTO INTERNO E CIENCIA DA EQUIPE','OUTROS','REGISTRO - Treinamento Interno e Ciência da Equipe','OUTROS'),
('cmr3d2mzx000004jrc6k3w8nb','REGULAMENTO INTERNO PROFISSIONAIS PARCEIROS E USO COMPARTILHADO DO ESPACO','OUTROS','Regulamento Interno de Profissionais Parceiros e Uso Compartilhado do Espaço','OUTROS'),
('cmszzcwgl000204lcw16snhy1','Relacao Profissionais Atuantes','OUTROS','Relação de Profissionais Atuantes','OUTROS'),
('cmp161q9i0027ewyxpo1yo4o5','Relacao Servicos Equipamentos','OUTROS','Relação de Serviços e Equipamentos','OUTROS'),
('cmu5ckacz000e04l5q3sxhoqd','TCLE - ACUPUNTURA','TCLE','TCLE - Acupuntura','TCLE'),
('cmr6b49cv000704kyar6g0xuq','TCLE ADMINISTRACAO ANESTESICO LOCAL','TCLE','TCLE - Administração de Anestésico Local','TCLE'),
('cmrdf1uzf000304l2g4q47bf3','TCLE - ADMINISTRACAO DE MEDICAMENTOS IM E EV','TCLE','TCLE - Administração de Medicamentos IM e EV','TCLE'),
('cmqr7b8lr000504l1ydnuradh','TCLE ALTA FREQUENCIA','TCLE','TCLE - Alta Frequência','TCLE'),
('cmqr7bby3000704l11yy7nyib','TCLE APLICACAO DE ENZIMAS','TCLE','TCLE - Aplicação de Enzimas','TCLE'),
('cmr2hy4yo000804jruopqkbzb','TCLE - AROMATERAPIA','TCLE','TCLE - Aromaterapia','TCLE'),
('cmr2hy2yt000704jrkanyf2j6','TCLE - AURICULOTERAPIA','TCLE','TCLE - Auriculoterapia','TCLE')
) v(id,nome_atual,tipo_atual,nome_novo,tipo_novo)
where t.id=v.id and t.nome=v.nome_atual and t.tipo=v.tipo_atual
;

update "Template" t set nome=v.nome_novo, tipo=v.tipo_novo
from (values
('cmu5cjw83000404l547nez901','TCLE - AVALIACAO CAPILAR','TCLE','TCLE - Avaliação Capilar','TCLE'),
('cmp161q9v0028ewyxl3074ll5','TCLE BB Glow','TCLE','TCLE - BB Glow','TCLE'),
('cmp161qa80029ewyxvnqy5mri','TCLE Bioestimuladores Colageno','TCLE','TCLE - Bioestimuladores de Colágeno','TCLE'),
('cmr2hy6vv000904jrsbjkkxec','TCLE - BIORREMODELADORES TECIDUAIS','TCLE','TCLE - Biorremodeladores Teciduais','TCLE'),
('cmr2hy1bz000604jr81liouvo','TCLE - BODY PIERCING','TCLE','TCLE - Body Piercing','TCLE'),
('cmqzbym5g000204kzxgqj5t56','TCLE BOTA COMPRESSIVA PRESSOTERAPIA','TCLE','TCLE - Bota Compressiva (Pressoterapia)','TCLE'),
('cmszzcrij000104i5ldt9p18h','TCLE - BROW LAMINATION','TCLE','TCLE - Brow Lamination','TCLE'),
('cmqr7b6u2000404l119z4h3d3','TCLE CARBOXITERAPIA','TCLE','TCLE - Carboxiterapia','TCLE'),
('cmqfohor3000b04kwzv158vws','TCLE CAVITACAO LIPO SEM CORTE','TCLE','TCLE - Cavitação (Lipo sem Corte)','TCLE'),
('cmr2jsyee000104l1tp3g4kgh','TCLE - CAVITACAO ULTRASSONICA','TCLE','TCLE - Cavitação Ultrassônica','TCLE'),
('cmqfoh9a1000104kwvm274tc8','TCLE CLAREAMENTO DE MELASMA MELANOSE E MANCHAS SENIS','TCLE','TCLE - Clareamento de Melasma, Melanose e Manchas Senis','TCLE'),
('cmqr7b1gi000104l1r5j5pdhk','TCLE CLAREAMENTO INTIMO','TCLE','TCLE - Clareamento Íntimo','TCLE'),
('cmr6d77j8000004jm0zr3db21','TCLE COLETA CITOPATOLOGICO MEIO LIQUIDO DNA HPV','TCLE','TCLE - Coleta de Citopatológico em Meio Líquido e DNA-HPV','TCLE'),
('cmr6b47la000604ky7akti3gr','TCLE CONSULTA ENFERMAGEM SAUDE MULHER SAUDE REPRODUTIVA','TCLE','TCLE - Consulta de Enfermagem em Saúde da Mulher e Saúde Reprodutiva','TCLE'),
('cmu5cjt8e000204l5hs54kxtd','TCLE - CONSULTA E ACOMPANHAMENTO FARMACEUTICO','TCLE','TCLE - Consulta e Acompanhamento Farmacêutico','TCLE'),
('cmu5cjurv000304l5a8v5xjvf','TCLE - CONSULTA E ACOMPANHAMENTO NUTRICIONAL','TCLE','TCLE - Consulta e Acompanhamento Nutricional','TCLE'),
('cmqfohn4h000a04kwl55tx3ni','TCLE CORRENTE RUSSA ELETROESTIMULACAO','TCLE','TCLE - Corrente Russa (Eletroestimulação)','TCLE'),
('edbc23c5-f11d-403d-978e-1231b5abfee4','TCLE - CRIOLIPOLISE','TCLE','TCLE - Criolipólise','TCLE'),
('cmtcu41g3000004l1cqblai1e','TCLE - CURATIVO E CUIDADOS COM FERIDAS','TCLE','TCLE - Curativo e Cuidados com Feridas','TCLE'),
('cmquuqm7s000704k1c0ge3nfq','TCLE DEPILACAO A CERA','TCLE','TCLE - Depilação à Cera','TCLE'),
('cmqfohito000704kwwt46c4ug','TCLE DEPILACAO A LASER','TCLE','TCLE - Depilação a Laser','TCLE'),
('cmqfohh2b000604kwm5z1pb89','TCLE DEPILACAO A LUZ PULSADA','TCLE','TCLE - Depilação à Luz Pulsada','TCLE'),
('cmqfohfnf000504kwmb813x44','TCLE DERMAPLANING','TCLE','TCLE - Dermaplaning','TCLE'),
('cmquuqegr000004k1swor0ccb','TCLE DESIGN DE SOBRANCELHAS','TCLE','TCLE - Design de Sobrancelhas','TCLE'),
('cmr2hxznz000504jrcogz1yfp','TCLE - DRENAGEM LINFATICA','TCLE','TCLE - Drenagem Linfática','TCLE'),
('cmquwt2q0000004jvt68d8qqb','TCLE DRENAGEM LINFATICA POS OPERATORIO ESTETICA','TCLE','TCLE - Drenagem Linfática no Pós-operatório Estético','TCLE'),
('cmujm0ngv000104l25ax7l8v0','TCLE - ELETROLIFTING','TCLE','TCLE - Eletrolifting','TCLE'),
('cmu5cjzcs000604l5pnu3974k','TCLE - ELETROPORACAO ESTETICA FACIAL CORPORAL E CAPILAR','TCLE','TCLE - Eletroporação Estética Facial, Corporal e Capilar','TCLE'),
('cmqsizf5m000004lbc6pg3bbu','TCLE ENDERMOTERAPIA','TCLE','TCLE - Endermoterapia','TCLE'),
('cmu5el2is000504l6duxghul6','TCLE - EPILACAO A CERA','TCLE','TCLE - Epilação à Cera','TCLE'),
('b6c08559-7933-43b7-89e0-fc4c7be7e727','TCLE - ESTETICA INTIMA','TCLE','TCLE - Estética Íntima','TCLE'),
('cmp161qan002aewyxj8lz6ajs','TCLE Estrias Plasma Bioestimulador','TCLE','TCLE - Estrias com Plasma Bioestimulador','TCLE'),
('cmpwyg973000004l8l6uog4zt','TCLE EXTENSAO DE CILIOS','TCLE','TCLE - Extensão de Cílios','TCLE'),
('cmppjksvl000004kvgmzbhjc9','TCLE - FIOS DE PDO','TCLE','TCLE - Fios de PDO','TCLE'),
('cmp2wj98w0003vkyx94n04afb','TCLE Fios de Sustentacao de PDO','TCLE','TCLE - Fios de Sustentação de PDO','TCLE'),
('cmp2wj9990004vkyx1mvom0x9','TCLE Fotobiomodulacao Laserterapia','TCLE','TCLE - Fotobiomodulação (Laserterapia)','TCLE'),
('cmqr7baio000604l1ayo2z8g9','TCLE FOTOTERAPIA COM LED E LUZ INTENSA PULSADA','TCLE','TCLE - Fototerapia com LED e Luz Intensa Pulsada','TCLE'),
('cmppjkuw6000304kvn5pre4qu','TCLE - FURO DE ORELHA BEBES','TCLE','TCLE - Furo de Orelha em Bebês','TCLE'),
('cmppjku31000204kv0eq3e7e3','TCLE - FURO HUMANIZADO E PIERCING ADULTOS','TCLE','TCLE - Furo Humanizado e Piercing em Adultos','TCLE'),
('cmp161qbw002dewyxhbmoeiw7','TCLE Harmonizacao Plasma Gel','TCLE','TCLE - Harmonização com Plasma Gel','TCLE'),
('cmp161qbe002cewyxu5n0k1i0','TCLE Harmonizacao Gluteos','TCLE','TCLE - Harmonização de Glúteos','TCLE'),
('cmp161qaz002bewyx22jtfb3y','TCLE Harmonizacao Facial','TCLE','TCLE - Harmonização Facial','TCLE'),
('cmp161qc8002eewyxxuj1xfn7','TCLE Hemoderivados PRP PRF','TCLE','TCLE - Hemoderivados (PRP e PRF)','TCLE'),
('36b1d393-1b1f-49c3-9624-9c5fb14e6964','TCLE - HIDROLIPOCLASIA','TCLE','TCLE - Hidrolipoclasia','TCLE'),
('cmq9g7ccu000304kyk01gm9dh','TCLE HIFU ULTRASSOM MACRO E MICROFOCADO','TCLE','TCLE - HIFU (Ultrassom Macro e Microfocado)','TCLE'),
('cmu2mbypa000304la1lu6p3x8','TCLE - INFILTRACAO INTRA ARTICULAR E PERIARTICULAR','TCLE','TCLE - Infiltração Intra-articular e Periarticular','TCLE'),
('cmr6b45sz000504kyy897g0iv','TCLE INSERCAO DISPOSITIVO INTRAUTERINO DIU','TCLE','TCLE - Inserção de Dispositivo Intrauterino (DIU)','TCLE'),
('cmr6b43tf000404kymgsq34w8','TCLE INSERCAO IMPLANTE CONTRACEPTIVO SUBDERMICO IMPLANON NXT','TCLE','TCLE - Inserção de Implante Contraceptivo Subdérmico (Implanon NXT)','TCLE'),
('cmp2wj99o0005vkyxuwavrjnf','TCLE Jato de Plasma','TCLE','TCLE - Jato de Plasma','TCLE'),
('cmqfoheba000404kwhq4e7a32','TCLE JATO DE PLASMA BLEFAROPLASTIA SEM CORTE','TCLE','TCLE - Jato de Plasma para Blefaroplastia sem Corte','TCLE'),
('cmqfohcti000304kw0027ivb0','TCLE JATO DE PLASMA REMOCAO DE SINAIS E PEQUENAS VERRUGAS','TCLE','TCLE - Jato de Plasma para Remoção de Sinais e Pequenas Verrugas','TCLE'),
('cmqr7b57t000304l14ol2bdti','TCLE LASER CO2 E LASER CO2 FRACIONADO','TCLE','TCLE - Laser CO2 e Laser CO2 Fracionado','TCLE'),
('cmqr7b3bb000204l1z86e8fzb','TCLE LASER LAVIEEN LASER DE TULIO 1927NM','TCLE','TCLE - Laser Lavieen (Laser de Túlio 1927 nm)','TCLE'),
('cmppjwnsb000604kv9hvo2xhr','TCLE - LASERTERAPIA POS PROCEDIMENTO','TCLE','TCLE - Laserterapia Pós-procedimento','TCLE'),
('cmszzcq2m000004i5p3ns3jpw','TCLE - LASH LIFTING','TCLE','TCLE - Lash Lifting','TCLE'),
('cmszzcyd6000304lch02qcrg4','TCLE LIBERACAO MIOFASCIAL COM VENTOSA','TCLE','TCLE - Liberação Miofascial com Ventosa','TCLE'),
('cmp161qcj002fewyx9xqf2m2v','TCLE Limpeza Pele','TCLE','TCLE - Limpeza de Pele','TCLE'),
('cmq9g7dma000604kyntf9fy3v','TCLE LIPO ENZIMATICA','TCLE','TCLE - Lipo Enzimática','TCLE'),
('932cee71-0b75-45b9-bf3d-d745179a6e26','TCLE - LIPO ENZIMATICA PAPADA','TCLE','TCLE - Lipo Enzimática de Papada','TCLE'),
('cmpwygaso000404l8ydm1wr1l','TCLE LOBULOMODELACAO LOBULOPLASTIA NAO CIRURGICA','TCLE','TCLE - Lobulomodelação (Lobuloplastia Não Cirúrgica)','TCLE'),
('cmu5cjy0b000504l56c48hwbe','TCLE - MANICURE E PEDICURE','TCLE','TCLE - Manicure e Pedicure','TCLE'),
('cmqfohlua000904kw0u63354d','TCLE MANTA TERMICA E PROTOCOLOS CORPORAIS ASSOCIADOS','TCLE','TCLE - Manta Térmica e Protocolos Corporais Associados','TCLE'),
('cmr2hxy66000404jrtn3zhe6p','TCLE - MASSAGEM MODELADORA','TCLE','TCLE - Massagem Modeladora','TCLE'),
('cmquvp85q000004jrpz8d8pvy','TCLE MASSAGEM TERAPEUTICA RELAXANTE E REDUTOR','TCLE','TCLE - Massagem Terapêutica Relaxante e Redutora','TCLE'),
('cmrm48x0i000004jt8ysu9ojy','TCLE - MESOTERAPIA E INTRADERMOTERAPIA CAPILAR','TCLE','TCLE - Mesoterapia e Intradermoterapia Capilar','TCLE'),
('cmrm491ox000204jt5hplu9y6','TCLE - MESOTERAPIA E INTRADERMOTERAPIA FACIAL E CORPORAL','TCLE','TCLE - Mesoterapia e Intradermoterapia Facial e Corporal','TCLE'),
('cmp2wj9a00006vkyxetf0k89r','TCLE Mesoterapia Intradermoterapia Skinbooster','TCLE','TCLE - Mesoterapia, Intradermoterapia e Skinbooster','TCLE'),
('cmp161qcv002gewyxhq5w9g6t','TCLE MICROAGULHAMENTO DRUG','TCLE','TCLE - Microagulhamento com Drug Delivery','TCLE'),
('cmp161qd7002hewyxysmkhnsg','TCLE Micropigmentacao','TCLE','TCLE - Micropigmentação','TCLE'),
('cmquuqkvy000604k12v894ccy','TCLE MICROPIGMENTACAO FACIAL','TCLE','TCLE - Micropigmentação Facial','TCLE'),
('2397a209-63d4-418d-a20d-2dac399a5e4f','TCLE - MICROTOX','TCLE','TCLE - Microtox','TCLE'),
('cmtcu430u000104l1o9rv6dsu','TCLE - NEBULIZACAO E INALOTERAPIA','TCLE','TCLE - Nebulização e Inaloterapia','TCLE'),
('05b5689d-fd81-4b48-9106-b7e7dc6a6292','TCLE - ONDAS DE CHOQUE','TCLE','TCLE - Ondas de Choque','TCLE'),
('cmpwygbrg000504l8wdkr9e4t','TCLE OTOMODELACAO','TCLE','TCLE - Otomodelação','TCLE'),
('cmppgtdtv000004jy4rl55egl','TCLE - OZONIOTERAPIA','TCLE','TCLE - Ozonioterapia','TCLE'),
('cmqsizkhq000304lbncvqnpon','TCLE PEELING ENZIMATICO','TCLE','TCLE - Peeling Enzimático','TCLE'),
('cmu4onpb4000004jtctyd4hd8','TCLE - PEELING FISICO MICRODERMOABRASAO','TCLE','TCLE - Peeling Físico (Microdermoabrasão)','TCLE'),
('cmujm0rr8000404l26cdy4ebk','TCLE - PEELING ULTRASSONICO','TCLE','TCLE - Peeling Ultrassônico','TCLE'),
('cmq9g7bgz000104kylmzq003v','TCLE PEELINGS ELETRICOS','TCLE','TCLE - Peelings Elétricos','TCLE'),
('cmp2wj9af0007vkyxo6t4qujh','TCLE Peelings Quimicos','TCLE','TCLE - Peelings Químicos','TCLE'),
('cmp2wj9at0008vkyxt3q0p19g','TCLE PEIM Escleroterapia','TCLE','TCLE - PEIM (Escleroterapia)','TCLE'),
('cmr2hxw5m000304jr9jeufxtn','TCLE - PERFURACAO AURICULAR HUMANIZADA LOBULO E CARTILAGEM','TCLE','TCLE - Perfuração Auricular Humanizada de Lóbulo e Cartilagem','TCLE'),
('cmt00mcoa000004iamgjvvq2w','TCLE PLASTICA DOS PES','TCLE','TCLE - Plástica dos Pés','TCLE'),
('cmquuqnj2000804k1kmd93wkd','TCLE PODOLOGIA','TCLE','TCLE - Podologia','TCLE'),
('07396008-ec7e-4b88-a770-4c5cb6523bb5','TCLE - PREENCHIMENTO DERMICO','TCLE','TCLE - Preenchimento Dérmico','TCLE'),
('cmp161qdk002iewyxi40mvnv2','TCLE Preenchimento Labial','TCLE','TCLE - Preenchimento Labial','TCLE'),
('cmqwf7xf8000204jsty4u8wi7','TCLE PROTOCOLO POS OPERATORIO ESTETICO','TCLE','TCLE - Protocolo Pós-operatório Estético','TCLE'),
('cmr2hxudo000204jrjnznkwis','TCLE - PRP PLASMA GEL E BIOESTIMULACAO AUTOLOGA','TCLE','TCLE - PRP, Plasma Gel e Bioestimulação Autóloga','TCLE'),
('cmq9g7d7z000504ky6yt4q94e','TCLE PUMP UP NOS GLUTEOS','TCLE','TCLE - Pump Up nos Glúteos','TCLE'),
('cmqsizh2w000104lba42h1tqu','TCLE RADIOFREQUENCIA','TCLE','TCLE - Radiofrequência','TCLE'),
('cmqfohqd5000c04kwjc7vvkqk','TCLE RADIOFREQUENCIA CORPORAL ENDERMOTERAPIA FLACIDEZ CELULITE E LIPEDEMA','TCLE','TCLE - Radiofrequência Corporal e Endermoterapia para Flacidez, Celulite e Lipedema','TCLE'),
('cmq9g7byy000204ky3rww2v7g','TCLE RADIOFREQUENCIA INTIMA','TCLE','TCLE - Radiofrequência Íntima','TCLE'),
('cmqwf7vv1000104jsesb1gj30','TCLE REDUCAO DE MEDIDAS PROTOCOLO COMBINADO','TCLE','TCLE - Redução de Medidas (Protocolo Combinado)','TCLE'),
('cmtu622ch000304ie0yogpnod','TCLE - REFLEXOTERAPIA PODAL','TCLE','TCLE - Reflexoterapia Podal','TCLE'),
('cmr2hxqlz000004jrndndi222','TCLE - REJUVENESCIMENTO INTIMO EXTERNO','TCLE','TCLE - Rejuvenescimento Íntimo Externo','TCLE'),
('cmr9duihf000104kvdmjma16f','TCLE - REMOCAO DE PIGMENTACAO ESTETICA','TCLE','TCLE - Remoção de Pigmentação Estética','TCLE'),
('cmr2hxskr000104jr1oz5lrb0','TCLE - REVITALIZACAO CORRECAO E FECHAMENTO DE LOBULO AURICULAR','TCLE','TCLE - Revitalização, Correção e Fechamento de Lóbulo Auricular','TCLE'),
('cmp161qe0002jewyx49u3o31n','TCLE Rinomodelacao','TCLE','TCLE - Rinomodelação','TCLE'),
('cmqr7bdqa000804l1lmt9xfwu','TCLE SKINBOOSTER','TCLE','TCLE - Skinbooster','TCLE'),
('cmu5el09x000304l6f1ujtlys','TCLE - SPA DOS PES PLASTICA DOS PES','TCLE','TCLE - Spa dos Pés (Plástica dos Pés)','TCLE'),
('cmsvr29sq000104l1bab1m8kg','TCLE - SUBCISAO','TCLE','TCLE - Subcisão','TCLE'),
('cmppjkth1000104kv1dol5vom','TCLE - TAPING POS CIRURGICO','TCLE','TCLE - Taping Pós-cirúrgico','TCLE'),
('cmtu61yv0000104ieicr97yv8','TCLE - TECARTERAPIA','TCLE','TCLE - Tecarterapia','TCLE'),
('cmqfoh52e000004l5wy3t3bhw','TCLE TERAPIA CAPILAR ALOPECIA E CALVICIE','TCLE','TCLE - Terapia Capilar para Alopecia e Calvície','TCLE'),
('cmtu6269b000504ieo6gnn3g2','TCLE - TERAPIA DE FLORAIS','TCLE','TCLE - Terapia de Florais','TCLE'),
('cmp2wj9b70009vkyxejr51jle','TCLE Terapia Injetavel Administracao Medicamentos','TCLE','TCLE - Terapia Injetável e Administração de Medicamentos','TCLE'),
('cmp2wj9bl000avkyxgx8limsk','TCLE Terapia Ortomolecular Suplementacao Intravenosa','TCLE','TCLE - Terapia Ortomolecular e Suplementação Intravenosa','TCLE'),
('cmqfohkfj000804kw3jbuk9im','TCLE TERAPIAS MANUAIS CORPORAIS MASSAGEM DRENAGEM LINFATICA E VENTOSATERAPIA','TCLE','TCLE - Terapias Manuais Corporais (Massagem, Drenagem Linfática e Ventosaterapia)','TCLE'),
('cmq9g7cr1000404kytnld2faf','TCLE TERAPIAS REGENERATIVAS PDRN EXOSSOMOS','TCLE','TCLE - Terapias Regenerativas (PDRN e Exossomos)','TCLE'),
('cmp161qed002kewyx5hmufepz','TCLE TOXINA BOTULINICA','TCLE','TCLE - Toxina Botulínica','TCLE'),
('cmqfoh7kp000004kwxfr1cojd','TCLE TRATAMENTO DE CICATRIZES DE ACNE','TCLE','TCLE - Tratamento de Cicatrizes de Acne','TCLE'),
('cmqfohb1g000204kwmlac6h4l','TCLE TRATAMENTO DE ESTRIAS','TCLE','TCLE - Tratamento de Estrias','TCLE'),
('cmqux05ko000104jvcnnusw0q','TCLE ULTRASSOM ESTETICO','TCLE','TCLE - Ultrassom Estético','TCLE'),
('cmp161qen002lewyxe61mu2gt','TCLE Uso Imagem LGPD','TCLE','TCLE - Uso de Imagem (LGPD)','TCLE'),
('cmqsiziqf000204lb21sgmhfq','TCLE VAPOR DE OZONIO','TCLE','TCLE - Vapor de Ozônio','TCLE'),
('cmu5ekxic000104l6vqdut9pt','TCLE - VENTOSATERAPIA','TCLE','TCLE - Ventosaterapia','TCLE'),
('cmu5cjrmx000104l520ft5yjl','TERMO DE CIENCIA E CONSENTIMENTO PARA AVALIACAO POR BIOIMPEDANCIA','TERMO','TERMO - Ciência e Consentimento para Avaliação por Bioimpedância','TERMO'),
('cmp161qez002mewyxcmsyv3h2','Termo Renuncia Recusa Tratamento','TERMO','TERMO - Renúncia e Recusa de Tratamento','TERMO')
) v(id,nome_atual,tipo_atual,nome_novo,tipo_novo)
where t.id=v.id and t.nome=v.nome_atual and t.tipo=v.tipo_atual
;

commit;
